//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projet_Livraison.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Livraison
    {
        public int Id_Livraison { get; set; }
        public string Reference { get; set; }
        public string Lieu { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<int> ClientId { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
